spring.application.name=product-service
server.port=8080

# MongoDB (?ã b? ch? .data theo chu?n phiên b?n m?i)
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=product-service
spring.mongodb.username=root
spring.mongodb.password=123456
spring.mongodb.authentication-database=admin